# Uncomment the next line to define a global platform for your project
project 'FirebaseApp.xcodeproj'
platform :ios, '10.0'

target 'FirebaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cmi
  pod 'Firebase/Core', '~> 5.6.0'
  pod 'Firebase/Auth', '~> 5.6.0'
  # pod 'Firebase/Database', '~> 5.6.0'
  pod 'Firebase/DynamicLinks', '~> 5.6.0'
  pod 'Firebase/Invites', '~> 5.6.0'
  # pod 'Firebase/Messaging', '~> 5.6.0'
  # pod 'Firebase/Storage', '~> 5.6.0'

  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'

  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

